---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-be
  labels:
    app: mlflow-be
spec:
  replicas: 10
  selector:
    matchLabels:
      app: mlflow-be
  template:
    metadata:
      labels:
        app: mlflow-be
    spec:
      containers:
        - name: mlflow-be-container
          image: olawalekareemdev/house-price-model:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-be-service
spec:
  type: NodePort
  selector:
    app: mlflow-be
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30200


    