name: MLOps CI FE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # workflow_dispatch: {}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@V3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r streamlit_app/requirements.txt


    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3


    - name: Build and push
      run: |
        COMMIT_HASH=$(echo ${{ github.sha }} | cut -c1-7)
        docker build  \
        -t docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model-frontend:$COMMIT_HASH \
        -t docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model-frontend:latest \
        docker push docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model-frontend:$COMMIT_HASH
        docker push docker.io/${{ vars.DOCKERHUB_USERNAME }}/house-price-model-frontend:latest
        








    

