name: MLOps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@V3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |
        pip install uv
        uv venv
        source .venv/bin/activate
        uv pip install -r requirements.txt

        uv pip list | grep pandas

    - name: Run Data Processing Tasks
      run: |
        source .venv/bin/activate
        python src/data/run_processing.py \
        --input data/raw/house_data.csv  \
        --output data/processed/cleaned_house_data.csv

    - name: Run Feature Engineering Tasks
      run: |
        python src/features/engineer.py \
        --input data/processed/cleaned_house_data.csv \
        --output data/processed/featured_house_data.csv  \
        --preprocessor models/trained/preprocessor.pkl


    - name: Run Model Training Tasks
      run: |
        python src/models/train_model.py \
        --config configs/model_config.yaml  \
        --data data/processed/featured_house_data.csv
        --models-dir models   --mlflow-tracking-uri http://localhost:5555







    

