name: MLOps CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@V3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Dependencies
      run: |

        # pip install uv
        # uv venv
        # source .venv/bin/activate
        # uv pip install -r requirements.txt
        # uv pip list | grep pandas


        python -m pip install --upgrade pip
        pip install -r requirements.txt


    - name: Run Data Processing Tasks
      run: |
        python src/data/run_processing.py \
        --input data/raw/house_data.csv  \
        --output data/processed/cleaned_house_data.csv

    - name: Run Feature Engineering Tasks
      run: |
        python src/features/engineer.py \
        --input data/processed/cleaned_house_data.csv \
        --output data/processed/featured_house_data.csv  \
        --preprocessor models/trained/preprocessor.pkl

    - name: Setup MlFlow Server
      run: |
        docker pull ghcr.io/mlflow/mlflow:latest
        docker run -d -p 5555:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
        mlflow server --host 0.0.0.0 \
        --backend-store-uri sqlite:///mlflow.db \
        --default-artifact-root /tmp/mlruns

    - name: Run Model Training Tasks
      run: |
        python src/models/train_model.py \
        --config configs/model_config.yaml  \
        --data data/processed/featured_house_data.csv
        --models-dir models   --mlflow-tracking-uri http://localhost:5555

    - name: Clean MlFlow Server
      run: |
        docker stop mlflow-server
        docker rm mlflow-server






    

